/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Tool = IDL.Record({
  'id' : IDL.Nat,
  'websiteUrl' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'logoEmoji' : IDL.Text,
  'dateAdded' : IDL.Int,
});

export const idlService = IDL.Service({
  'addPendingTool' : IDL.Func([Tool], [], []),
  'addTool' : IDL.Func([Tool], [], []),
  'getAllTools' : IDL.Func([], [IDL.Vec(Tool)], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getLatestTools' : IDL.Func([IDL.Nat], [IDL.Vec(Tool)], ['query']),
  'getToolsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Tool)], ['query']),
  'searchTools' : IDL.Func([IDL.Text], [IDL.Vec(Tool)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Tool = IDL.Record({
    'id' : IDL.Nat,
    'websiteUrl' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'logoEmoji' : IDL.Text,
    'dateAdded' : IDL.Int,
  });
  
  return IDL.Service({
    'addPendingTool' : IDL.Func([Tool], [], []),
    'addTool' : IDL.Func([Tool], [], []),
    'getAllTools' : IDL.Func([], [IDL.Vec(Tool)], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getLatestTools' : IDL.Func([IDL.Nat], [IDL.Vec(Tool)], ['query']),
    'getToolsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Tool)], ['query']),
    'searchTools' : IDL.Func([IDL.Text], [IDL.Vec(Tool)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };